const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const REMOVE_ALL_ITEMS = "REMOVE_ALL_ITEMS";

const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export { ADD_TO_CART, REMOVE_CART_ITEM, REMOVE_ALL_ITEMS, SAVE_SHIPPING_INFO };