const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
const MY_ORDERS_FAILURE = "MY_ORDERS_FAILURE";

const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
const ORDER_DETAIL_FAILURE = "ORDER_DETAIL_FAILURE";


const CLEAR_ERRORS = "CLEAR_ERRORS";

export { CREATE_ORDER_REQUEST, CREATE_ORDER_SUCCESS, CREATE_ORDER_FAILURE, MY_ORDERS_FAILURE, MY_ORDERS_REQUEST, MY_ORDERS_SUCCESS, ORDER_DETAIL_FAILURE, ORDER_DETAIL_REQUEST, ORDER_DETAIL_SUCCESS, CLEAR_ERRORS };