const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
const ALL_PRODUCT_FAILURE = "ALL_PRODUCT_FAILURE";

const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE";

const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE";


const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
const NEW_PRODUCT_FAILURE = "NEW_PRODUCT_FAILURE";

const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
const NEW_REVIEW_FAILURE = "NEW_REVIEW_FAILURE";

const CLEAR_ERRORS = "CLEAR_ERRORS";

export { ALL_PRODUCT_FAILURE, ALL_PRODUCT_REQUEST, ALL_PRODUCT_SUCCESS, PRODUCT_DETAILS_FAILURE, PRODUCT_DETAILS_SUCCESS, PRODUCT_DETAILS_REQUEST, ADMIN_PRODUCT_FAILURE, ADMIN_PRODUCT_REQUEST, ADMIN_PRODUCT_SUCCESS, NEW_PRODUCT_FAILURE, NEW_PRODUCT_REQUEST, NEW_PRODUCT_SUCCESS, NEW_PRODUCT_RESET, NEW_REVIEW_FAILURE, NEW_REVIEW_REQUEST, NEW_REVIEW_SUCCESS, NEW_REVIEW_RESET, CLEAR_ERRORS };