const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

const CLEAR_ERRORS = "CLEAR_ERRORS";

export { UPDATE_PROFILE_FAILURE, UPDATE_PROFILE_REQUEST, UPDATE_PROFILE_RESET, UPDATE_PROFILE_SUCCESS, CLEAR_ERRORS };