const STRIPE_KEY_REQUEST = "STRIPE_KEY_REQUEST";
const STRIPE_KEY_SUCCESS = "STRIPE_KEY_SUCCESS";
const STRIPE_KEY_FAILURE = "STRIPE_KEY_FAILURE";

const CLEAR_ERRORS = "CLEAR_ERRORS";

export { STRIPE_KEY_REQUEST, STRIPE_KEY_SUCCESS, STRIPE_KEY_FAILURE, CLEAR_ERRORS };